// <auto-generated />
namespace EmpyreBookApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class zach417_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zach417_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201404170848417_zach-4-17_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
